obj-$(CONFIG_SEC_LOG)           += sec-log.o
obj-$(CONFIG_SEC_DEBUG)         += sec-debug.o sec-getlog.o sec-gaf.o sec-ftrace.o
obj-$(CONFIG_MACH_PXA_SAMSUNG)  += sec-common.o
obj-$(CONFIG_EXTCON_S2MM001)	+= s2mm001.o
obj-$(CONFIG_EXTCON_SM5504)	+= extcon-sm5504.o
obj-$(CONFIG_EXTCON_SM5502)	+= extcon-sm5502.o
obj-$(CONFIG_SEC_FACTORY)	+= sec-factoryled.o
obj-$(CONFIG_SEC_BSP)		+= sec-bsp.o
